# Generated by Django 2.2.1 on 2019-07-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=80)),
                ('uploadername', models.CharField(max_length=80)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='LoginRegister.User')),
            ],
        ),
    ]
