# Generated by Django 2.1.5 on 2019-07-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0001_initial'),
    ]

    operations = [
    ]
