# Generated by Django 2.1.5 on 2019-07-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0002_auto_20190708_2221'),
    ]

    operations = [
    ]
