# Generated by Django 2.1.10 on 2019-07-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0003_auto_20190708_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': '云文件'},
        ),
        migrations.AlterField(
            model_name='file',
            name='fid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=80, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='LoginRegister.User', verbose_name='上传者'),
        ),
    ]
