# Generated by Django 2.1.5 on 2019-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0003_user_has_confiremed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgpath',
            field=models.CharField(default='moren/moren123.jpg', max_length=80),
        ),
    ]
