# Generated by Django 2.1.5 on 2019-07-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0005_auto_20190708_2221'),
    ]

    operations = [
    ]
