# Generated by Django 2.1.10 on 2019-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0006_auto_20190708_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.IntegerField(default=50, verbose_name='可用空间'),
        ),
        migrations.AddField(
            model_name='user',
            name='used',
            field=models.IntegerField(default=0, verbose_name='已用空间'),
        ),
    ]
