# Generated by Django 2.1.5 on 2019-07-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginRegister', '0003_user_has_confiremed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('up_count', models.IntegerField(default=0)),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='回复内容')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Comment', verbose_name='回复评论')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='回复文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='回复用户')),
            ],
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_up', models.BooleanField(verbose_name='是否赞')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='赞用户')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='评论文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='评论者'),
        ),
    ]
