# Generated by Django 2.1.5 on 2019-07-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0004_auto_20190708_1408'),
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_collect', models.BooleanField(verbose_name='是否赞')),
            ],
        ),
        migrations.AddField(
            model_name='dynamic',
            name='collect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collect',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='赞用户'),
        ),
    ]
