# Generated by Django 2.1.5 on 2019-07-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20190708_2132'),
    ]

    operations = [
    ]
