# Generated by Django 2.1.10 on 2019-07-10 00:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20190708_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name_plural': '收藏记录表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name_plural': '动态'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': '回复'},
        ),
        migrations.AlterModelOptions(
            name='up',
            options={'verbose_name_plural': '点赞记录表'},
        ),
        migrations.AddField(
            model_name='reply',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collect',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='收藏动态'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='is_collect',
            field=models.BooleanField(verbose_name='收藏状态'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='收藏用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='所评动态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='collect_count',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='content',
            field=models.TextField(verbose_name='动态内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Comment', verbose_name='所回评论'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='所回动态'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='回复者'),
        ),
        migrations.AlterField(
            model_name='up',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find.Dynamic', verbose_name='点赞动态'),
        ),
        migrations.AlterField(
            model_name='up',
            name='is_up',
            field=models.BooleanField(verbose_name='点赞状态'),
        ),
        migrations.AlterField(
            model_name='up',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='up',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginRegister.User', verbose_name='点赞用户'),
        ),
    ]
